;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	indent-for-tab-command
	mark-whole-buffer
	))

(setq mc/cmds-to-run-once
      '(
	comment-dwim
	icicle-goto-marker-or-set-mark-command
	next-buffer
	))
